#!/bin/sh

LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")

wget --spider --quiet -T 3 www.google.com.hk
if [ "$?" == "0" ]; then
	echo "[$LOGTIME] No problem."
	exit 0
else
	wget --spider --quiet -T 3 www.baidu.com
	if [ "$?" == "0" ]; then
		echo "[$LOGTIME] Problem decteted, restart ShadowsocksR."
		/etc/init.d/shadowsocksr restart
		sleep 3
		wget --spider --quiet -T 3 www.google.com.hk
		if [ "$?" == "0" ]; then
			echo "[$LOGTIME] ShadowsocksR recovered."
			exit 0
		else
			echo "[$LOGTIME] ShadowsocksR can not recovered."
			exit 0
		fi
	else
		echo "[$LOGTIME] Network problem. Do nothing."
	fi
fi
